#!/bin/bash -xe

# Specify version on the command line
# For example:
# ./build 2.13.3

version=$1
directory="$(cd "$(dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)"

major=$(echo $version | cut -d '.' -f1,2)

echo "Creating directory for ${major}/${version}"
mkdir -p ${major}/${version}
cd ${major}/${version}

sudo dnf install -y python3-pip

pushd ${directory}/${major}/${version}
  cd /tmp
  rm -rf ansible/
  git clone https://github.com/ansible/ansible.git
  cd ansible/
  git checkout v${version}
  cd ..
  tar -czf ansible-${version}.tar.gz ansible/
popd

mv /tmp/ansible-${version}.tar.gz .
gpg2 --detach-sign --armor ansible-${version}.tar.gz > ansible-${version}.tar.gz.gpg


